version: "3"
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8088:8088"
    depends_on:
      - db
    volumes:
      - /var/lib/bober-chat/uploads:/var/www/html/uploads
  db:
    image: 'mariadb:latest'
    restart: unless-stopped
    ports:
      - "3366:3306"
    env_file:
      - .env
    volumes:
      - /var/lib/bober-chat/mysql:/var/lib/mysql
